// src/data/teamLogos.js
export const teamLogos = {
    //SuperLig Teams
    Besiktas: "/logos/besiktas.webp",
    Fenerbahce: "/logos/fenerbahçe.webp",
    Alanyaspor: "/logos/alanyaspor.webp",
    Galatasaray: "/logos/galatasaray.webp",
    Trabzonspor: "/logos/trabzonspor.webp",
    "Istanbul Basaksehir": "/logos/başakşehir.webp",
    Sivasspor: "/logos/sivasspor.webp",
    Kayserispor: "/logos/kayserispor.webp",
    Antalyaspor: "/logos/antalyaspor.webp",
    AdanaDemirspor: "/logos/adanademirspor.webp",
    Konyaspor: "/logos/konyaspor.webp",
    Giresunspor: "/logos/giresunspor.webp",
    "Caykur Rizespor": "/logos/rizespor.webp",
    Kasimpasa: "/logos/kasımpaşa.webp",
    Ümraniyespor: "/logos/umraniyespor.webp",
    "Fatih Karagümrük": "/logos/fatihkaragumruk.webp",
    Hatayspor: "/logos/hatayspor.webp",
    Denizlispor: "/logos/denizlispor.webp",
    Erzurumspor: "/logos/erzurumspor.webp",
    Sivasspor: "/logos/sivasspor.webp",
    Bursaspor: "/logos/bursaspor.webp",
    Samsunspor: "/logos/samsunspor.webp",
    Alanyaspor: "/logos/alanyaspor.webp",
    Malatyaspor: "/logos/malatyaspor.webp",
    Akhisarspor: "/logos/akhisarspor.webp",
    Kocaelispor: "/logos/kocaeli.webp",
    Eyupspor: "/logos/eyüpspor.webp",
    Genclerbirligi: "/logos/genclerbirliği.webp",
    Goztepe: "/logos/göztepe.webp",
    "Gaziantep FK": "/logos/gaziantep.png",  

    //Serie A Teams
    Juventus: "/logos/juventus.png",
    Milan: "/logos/milan.png",
};
